In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [2]:
x = [3, 4]
y = [5, 6]

x + y

[3, 4, 5, 6]

In [3]:
import numpy as np

In [4]:
x = np.array ([3, 4, 5])
y = np.array ([4, 9, 7])

In [5]:
x + y

array([ 7, 13, 12])

In [6]:
# Matrix
x = np.array ([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [15]:
# Attributes
x.ndim

2

In [10]:
x.dtype

dtype('int64')

In [11]:
np.array ([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [16]:
# Create a floating point array
np.array ([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [17]:
# Find out number of rows and columns
x.shape

(2, 2)

In [18]:
x = np.array ([1, 2, 3, 4])
x.sum()

10

In [19]:
# Reshape -> returns a new array with the same elements as x
# (2,3) -> specifies that we would like to create a 
# two-dimensional array with 2 rows and columsn

x = np.array ([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape ((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [20]:
x_reshape [0, 0]

1

In [21]:
x_reshape [1, 2]

6

In [23]:
# Modifying x_reshape also modified x because the two objects occupy the
# same space in memory.

print('x before we modify x_reshape :\n', x)
print('x_reshape before we modify x_reshape :\n', x_reshape)
x_reshape [0, 0] = 5
print('x_reshape after we modify its top left element :\n',
x_reshape)
print('x after we modify top left element of x_reshape :\n', x)

x before we modify x_reshape :
 [5 2 3 4 5 6]
x_reshape before we modify x_reshape :
 [[5 2 3]
 [4 5 6]]
x_reshape after we modify its top left element :
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape :
 [5 2 3 4 5 6]


In [27]:
#.T -> transpose
x_reshape.shape , x_reshape.ndim , x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [28]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [29]:
# Generate random variables
x = np.random.normal(size =50)
x

array([-0.24058816,  1.06372634, -0.43141136,  0.85914009, -0.204786  ,
       -1.15181229,  1.9581334 ,  0.53293345,  1.58326821, -0.89739476,
        0.36813788, -0.30450881,  0.60882548,  0.6288454 , -0.71205468,
        0.19225648,  0.84761529, -0.99770228,  1.9766292 ,  1.25079382,
       -1.50160429, -0.88096691,  1.79341832, -0.02969904, -1.49729985,
       -0.4436047 ,  0.87142389,  0.2047157 , -0.70019091, -0.26362863,
        0.22107224, -0.96528995,  1.49612261,  0.92022477,  0.46396538,
       -0.44633997,  1.15406843,  2.55747155, -0.40255062,  1.06915813,
        1.71835866,  1.28699851,  1.98106309,  1.73678058, -0.39892424,
       -0.22300758,  0.5658021 ,  0.67923531,  1.32281892, -0.95792476])

In [31]:
y = x + np.random.normal(loc=50, scale=1, size =50)
y

array([49.97957013, 48.41556516, 49.41953402, 50.23337052, 50.23174905,
       48.46129446, 50.86322546, 49.73858629, 49.95677837, 47.80342437,
       50.29480412, 49.51652958, 52.10349976, 51.52127866, 48.07250288,
       49.43967585, 50.4753562 , 51.04145291, 52.60502476, 52.02558365,
       48.01251125, 49.17407911, 53.33007615, 49.12703996, 48.66452498,
       50.81984138, 49.8177498 , 50.59772162, 49.52437922, 50.6877822 ,
       49.95502381, 50.93225102, 51.46244347, 51.0612559 , 50.78030258,
       51.41831047, 51.82992314, 54.27575429, 51.04458042, 51.67669087,
       51.74283461, 51.92533387, 51.87902131, 51.28415573, 49.51644051,
       49.04326171, 49.6357588 , 50.00553142, 51.50049651, 48.6053662 ])

In [32]:
# Compute Correlation Matrix Between x and y
np.corrcoef(x, y)

array([[1.        , 0.70910771],
       [0.70910771, 1.        ]])

In [34]:
# Give the same result for random numbers
rng = np.random.default_rng (1303)
print(rng.normal(scale=5, size =2))
rng2 = np.random.default_rng (1303)
print(rng2.normal(scale=5, size =2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [36]:
rng = np.random.default_rng (3)
y = rng.standard_normal (10)
np.mean(y), y.mean ()

(-0.1126795190952861, -0.1126795190952861)